interface MetadataTraits {
  Background: string[];
  Speciality: string[];
  Skin: string[];
  Clothes: string[];
  Beard: string[];
  Head: string[];
  Eyes: string[];
  Mustache: string[];
  Nose: string[];
  Coin: string[];
  Hands: string[];
}

const METADATA_TRAITS: MetadataTraits = {
  Background: [
    "Daylight.png",
    "Denim.png",
    "Dungeon.png",
    "Dust.png",
    "Graphite.png",
    "Grey.png",
    "Land.png",
    "Lavender.png",
    "Matcha.png",
    "Midnight.png",
    "Mystic Forest.png",
    "Ocean.png",
    "Salmon.png",
    "Strawberry.png",
    "Sunkist.png",
    "Sunset.png",
    "Violet.png",
    "White.png",
    "Wizard.png",
    "Yellow.png",
  ],
  Beard: [
    "Alien Dread.png",
    "Devil.png",
    "Egypt.png",
    "Elder.png",
    "Flame.png",
    "Gems.png",
    "Green.png",
    "Grey.png",
    "Hippie.png",
    "Ice King.png",
    "Mankind.png",
    "Mankind2.png",
    "Nature.png",
    "Nebula.png",
    "Obi Wan.png",
    "Professor.png",
    "Tentacels.png",
    "Tribe.png",
    "Wukong.png",
    "Zeus.png",
  ],
  Clothes: [
    "Apocalypse Gear.png",
    "Astrologer.png",
    "Blank.png",
    "Blue Coat.png",
    "Clown.png",
    "Darth Vader.png",
    "Devil.png",
    "Egypt Attire.png",
    "Fighter.png",
    "Goblin.png",
    "Grim Reaper Coat.png",
    "Hippie Attire.png",
    "Holy Suit.png",
    "Jedai Suit.png",
    "Lab Coat.png",
    "Mankind Suit.png",
    "Monk Attire.png",
    "Nature Coat.png",
    "Patched Coat.png",
    "Pirate.png",
    "Robe.png",
    "Seer.png",
    "Shroom Farmer.png",
    "Stargaze Coat.png",
    "Tribal Attire.png",
    "Zeus Suit.png",
  ],
  Coin: [
    "TEA.png",
    "ADA.png",
    "AKASH.png",
    "APE.png",
    "APT.png",
    "ARB.png",
    "ARC.png",
    "ATOM.png",
    "AVAX.png",
    "BASE.png",
    "BNB.png",
    "BONK.png",
    "BTC.png",
    "CHIHUAHUA.png",
    "DOGE.png",
    "DOT.png",
    "DYDX.png",
    "Dymension.png",
    "ELYS.png",
    "ETH.png",
    "Forma.png",
    "INJ.png",
    "Juno.png",
    "JUP.png",
    "Kujira.png",
    "Manta.png",
    "Mantra.png",
    "MONDA.png",
    "NEUTRON.png",
    "NOBE.png",
    "OMNI.png",
    "OSMO.png",
    "POLY.png",
    "SAGA.png",
    "SEI.png",
    "SHITMOS.png",
    "SOL.png",
    "STARS.png",
    "SUI.png",
    "Territori.png",
    "TIA.png",
    "TRON.png",
    "UNICORN.png",
    "USDC.png",
    "XRP.png",
    "XTZ.png",
  ],
  Eyes: [
    "Alien.png",
    "Brown.png",
    "Bush.png",
    "Clown.png",
    "Devil.png",
    "Egypt.png",
    "Elder.png",
    "Eye Balls.png",
    "Fighter.png",
    "Flame.png",
    "Gods.png",
    "Grumpy.png",
    "Ice King.png",
    "Insane.png",
    "Intense.png",
    "Lightning.png",
    "Scary.png",
    "Sea-Monster.png",
    "Senior.png",
    "Shroom.png",
    "Third Sight.png",
    "Wukong.png",
  ],
  Hands: [
    "Alien.png",
    "Apocalypse.png",
    "Blank.png",
    "Chill.png",
    "Clown.png",
    "Devil Fork.png",
    "Flame.png",
    "Goblin Bomb.png",
    "Holy Cross.png",
    "Ice.png",
    "Lightbar.png",
    "Lightning Bolt.png",
    "Lightsaber.png",
    "Mage.png",
    "Magic Shroom.png",
    "Nebula.png",
    "Parrot.png",
    "Penguin.png",
    "Pharoah.png",
    "Reaper.png",
    "Red Lightsaber.png",
    "Scientist.png",
    "Spellcraft.png",
    "Tribe.png",
    "Trident.png",
    "Weird-Weed.png",
    "Weird.png",
    "Wizard.png",
    "Wood.png",
    "Wukong.png",
  ],
  Head: [
    "Alien.png",
    "Blank.png",
    "Blue Hippie.png",
    "Clown.png",
    "Cone.png",
    "Darth Vaderr.png",
    "Devil.png",
    "Flame.png",
    "Goblin.png",
    "Greek.png",
    "Hippie.png",
    "Joker.png",
    "King.png",
    "Mystery Ball.png",
    "Patched Beannie.png",
    "Pirate.png",
    "Scientist.png",
    "Shroom.png",
    "Skull.png",
    "Stargaze.png",
    "Wizard.png",
    "Wood.png",
    "Wukong.png",
  ],
  Mustache: [
    "Alien.png",
    "Brown.png",
    "Drac.png",
    "Egypt.png",
    "Elder.png",
    "Gandalf.png",
    "Goblin.png",
    "Grey Pade.png",
    "Hippie.png",
    "Ice King.png",
    "Joker.png",
    "Nature.png",
    "Nebula.png",
    "On-Fire.png",
    "Pade.png",
    "Scientist.png",
    "Survival.png",
    "Tentacles.png",
    "Tribe.png",
    "Weird.png",
    "Wukong.png",
    "Zeus.png",
  ],
  Nose: [
    "Alien.png",
    "Big.png",
    "Clown.png",
    "Damaged.png",
    "Devil.png",
    "Drac.png",
    "Emerald.png",
    "Ice King.png",
    "Magma.png",
    "Mankind G.png",
    "Mankind.png",
    "Mech.png",
    "Pyramid.png",
    "Shell.png",
    "Shroom.png",
    "Snotty.png",
    "Tribe.png",
    "Wizard.png",
    "Wood.png",
    "Wukong.png",
  ],
  Skin: [
    "Alien.png",
    "Bone.png",
    "Clown.png",
    "Croc.png",
    "Devil.png",
    "Drac.png",
    "Elder.png",
    "Elf.png",
    "Fish.png",
    "Flesh.png",
    "Golem.png",
    "Ice King.png",
    "Magma.png",
    "Mankind.png",
    "Mummy.png",
    "Nebula.png",
    "Night Owl.png",
    "Orc.png",
    "Robot.png",
    "Rune.png",
    "Stitch.png",
    "Tattoo.png",
    "Toy.png",
    "Wukong.png",
    "Yellow.png",
  ],
  Speciality: [
    "Blank.png",
    "Electro.png",
    "Geo.png",
    "Herbs Farm.png",
    "Hydro.png",
    "Rage.png",
    "z.png",
    "za.png",
    "zb.png",
    "zg.png",
    "zh.png",
    "zi.png",
    "zj.png",
    "zk.png",
    "zl.png",
    "zm.png",
  ],
};

export { METADATA_TRAITS };
